import org.apache.shiro.SecurityUtils

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {

    def userService

    def filters = {
        all(uri: "/**") {
            before = {
                def user = getUser(session)
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                // Access control by convention.
                accessControl()
            }
        }
    }

    private User getUser(session) {
        def user = userService.currentUser
        if (!user && SecurityUtils.subject.remembered) {
            user = userService.getUserWithCommonLogin(session)
        }
        return user
    }
}
